services:
  omron_moma:
    container_name: omron_moma
    image: ghcr.io/collaborativeroboticslab/omron_moma:humble
    environment:
      - PYTHONUNBUFFERED=1                # GUI related
      - DISPLAY                           # GUI related
      - QT_X11_NO_MITSHM=1                # GUI related
      - NVIDIA_VISIBLE_DEVICES=all        # GUI related
      - NVIDIA_DRIVER_CAPABILITIES=all    # GUI related
      - ROS_DOMAIN_ID=0
      - USE_RVIZ=true
      - USE_MOVEIT=true
      - USE_NAV2=true
      - ARM_USE_SIMULATION=false
    restart: unless-stopped
    privileged: true
    network_mode: host
    volumes:
      - /dev:/dev
      - /tmp/.X11-unix:/tmp/.X11-unix:rw    # GUI related